function verbose_none(params, population, evaluation, ...
                      selected_population, selected_evaluation, ...
                      sampled_population, sampled_evaluation)
  % Dummy verbose method. Prints nothing.                 
end
