function verbose_generation(params, generation, population, evaluation, ...
                            selected_population, selected_evaluation, ...
                            sampled_population, sampled_evaluation)
  % Prints statistical information on each generation.
  
  % Created by Yasser González Fernández (2010).
  
  fprintf('\nStatistics for generation %d:\n', generation);
  fprintf('  Population fitness: %f (%f)\n', ...
          mean(evaluation), std(evaluation));
  fprintf('  Selected population fitness: %f (%f)\n', ...
          mean(selected_evaluation), std(selected_evaluation));
  fprintf('  Sampled population fitness: %f (%f)\n', ...
          mean(sampled_evaluation), std(sampled_evaluation));
end
